export type AppSettings = {
  id: number;
  league_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  address?: string | null;
  address_line_2?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  website?: string | null;
  facebook_url?: string | null;
  instagram_url?: string | null;
  youtube_url?: string | null;
  tiktok_url?: string | null;
  logo_url?: string | null;
  primary_color?: string | null;
  secondary_color?: string | null;
  support_text?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};