alter table public.events
  add column if not exists membership_price numeric(10, 2) not null default 0;

alter table public.events
  add column if not exists event_price numeric(10, 2) not null default 0,
  add column if not exists stripe_product_id text,
  add column if not exists stripe_price_id text;

create table if not exists public.event_memberships (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  amount_paid numeric(10, 2) not null default 0,
  appearances_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_memberships_event_player_unique unique (event_id, player_id),
  constraint event_memberships_amount_paid_nonnegative check (amount_paid >= 0),
  constraint event_memberships_appearances_nonnegative check (appearances_count >= 0)
);

create index if not exists event_memberships_event_id_idx
  on public.event_memberships(event_id);

create index if not exists event_memberships_player_id_idx
  on public.event_memberships(player_id);
