create table if not exists public.team_playing_days (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  day_of_week integer not null check (day_of_week between 1 and 7),
  created_at timestamptz not null default now(),
  unique (team_id, day_of_week)
);

create index if not exists team_playing_days_day_of_week_team_id_idx
on public.team_playing_days (day_of_week, team_id);
